import indicesData from "../data/indices.json";
import countryRiskData from "../data/countryRisk.json";
import type { Mode } from "./types";

interface CountryScores {
  econ: number;
  security: number;
}

interface CountryRisk {
  securityDelta: number;
  econDelta: number;
}

const countries = indicesData.countries as Record<string, CountryScores>;
const cityEconomicBonus = indicesData.cityEconomicBonus as Record<string, number>;
const nodeSecurity = indicesData.nodeSecurity as Record<string, number>;
/** Live sanctions/conflict adjustment, generated by tools/fetchCountryRisk.mjs. Curated scores stay the source of truth; this only nudges them, within caps set there. */
const countryRisk = countryRiskData.countries as Record<string, CountryRisk>;

const DEFAULT_SCORES: CountryScores = { econ: 30, security: 50 };

const clamp = (value: number) => Math.max(0, Math.min(100, value));

export function economicIndex(nodeId: string, country: string): number {
  const base = (countries[country] ?? DEFAULT_SCORES).econ;
  return clamp(base + (cityEconomicBonus[nodeId] ?? 0) + (countryRisk[country]?.econDelta ?? 0));
}

/** A city can be materially safer or more dangerous than its country, and that hand-set override is the final word for that node — the live country adjustment applies to everywhere else. */
export function securityIndex(country: string, nodeId?: string): number {
  const override = nodeId === undefined ? undefined : nodeSecurity[nodeId];
  if (override !== undefined) return clamp(override);
  return clamp((countries[country] ?? DEFAULT_SCORES).security + (countryRisk[country]?.securityDelta ?? 0));
}

/** Below this a route is flagged and a safer alternative is offered. */
export const SECURITY_ALERT_THRESHOLD = 30;

/**
 * Security accumulated over every stop, weighted so the weakest link dominates:
 * one hostile transhipment point should sink a route that is otherwise safe,
 * while a route that is merely mediocre throughout still scores mediocre.
 */
export function routeSecurityIndex(stopScores: number[]): number {
  if (stopScores.length === 0) return 0;
  const worst = Math.min(...stopScores);
  const mean = stopScores.reduce((sum, s) => sum + s, 0) / stopScores.length;
  return Math.round(0.6 * worst + 0.4 * mean);
}

const ALL_MODES: Mode[] = ["sea", "air", "rail", "truck"];

/** 100 minus 15 points per transport mode not available at this node — a full multi-modal hub trades cargo between types easily, a single-mode node can't. */
export function transitIndex(availableModes: Mode[]): number {
  const missing = ALL_MODES.filter((m) => !availableModes.includes(m)).length;
  return Math.max(0, 100 - missing * 15);
}
