/**
 * Builds src/data/countryRisk.json: a live, bounded adjustment to the curated
 * security and economic scores in indices.json.
 *
 * The curated numbers are hand-reasoned and stay the source of truth — this
 * file only ever nudges them, within HARD caps, so a bad feed day can't
 * rewrite the model. Sources are folded together per country:
 *
 *   OpenSanctions - sanctioned targets registered to the country. Sanctions
 *                   raise the cost and risk of moving civilian freight through
 *                   an economy; they don't close a border, so this is a score
 *                   adjustment rather than a restriction.
 *   GDELT         - conflict-related coverage volume, best-effort.
 *
 * Only countries that actually have nodes are written, so the file stays small.
 *
 * Usage: node tools/fetchCountryRisk.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { readNodes } from "./lib/nodes.mjs";
import { fetchSanctionsByCountry } from "./feeds/opensanctions.mjs";
import { fetchConflictMentions } from "./feeds/gdelt.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Caps on how far live data may move a curated score.
const MAX_SANCTIONS_SECURITY_PENALTY = 18;
const MAX_SANCTIONS_ECON_PENALTY = 12;
const MAX_CONFLICT_SECURITY_PENALTY = 12;

// Designation counts are extremely skewed (Russia is in the thousands, most
// sanctioned states in the tens), so the penalty is logarithmic — the step from
// 10 to 100 designations means far more than 5,000 to 10,000.
const DESIGNATIONS_FULL_SCALE = 5000;

function sanctionsPenalty(entry, max) {
  if (!entry?.designations) return 0;
  const scaled = Math.log10(1 + entry.designations) / Math.log10(1 + DESIGNATIONS_FULL_SCALE);
  return Math.round(Math.min(1, scaled) * max);
}

function conflictPenalty(mentions, busiest) {
  if (!mentions || !busiest) return 0;
  return Math.round((mentions / busiest) * MAX_CONFLICT_SECURITY_PENALTY);
}

const nodes = readNodes(ROOT);
const countriesWithNodes = new Set(nodes.map((n) => n.country));

const sanctions = await fetchSanctionsByCountry().catch((err) => {
  console.error(`OpenSanctions fetch failed, no sanctions adjustment this run: ${err.message}`);
  return { byCountry: new Map(), updatedAt: null };
});

const conflict = await fetchConflictMentions().catch((err) => {
  console.error(`GDELT fetch failed, no conflict adjustment this run: ${err.message}`);
  return new Map();
});

const busiest = Math.max(0, ...conflict.values());

const countries = {};
for (const country of [...countriesWithNodes].sort()) {
  const sanctioned = sanctions.byCountry.get(country);
  const mentions = conflict.get(country) ?? 0;
  const securityDelta = -(
    sanctionsPenalty(sanctioned, MAX_SANCTIONS_SECURITY_PENALTY) + conflictPenalty(mentions, busiest)
  );
  const econDelta = -sanctionsPenalty(sanctioned, MAX_SANCTIONS_ECON_PENALTY);
  if (securityDelta === 0 && econDelta === 0) continue;

  countries[country] = {
    sanctionsPrograms: sanctioned?.programs ?? 0,
    sanctionsDesignations: sanctioned?.designations ?? 0,
    conflictMentions: mentions,
    securityDelta,
    econDelta,
  };
}

const out = {
  _methodology:
    "Generated by tools/fetchCountryRisk.mjs. securityDelta/econDelta are bounded adjustments applied on top of the curated scores in indices.json, never replacing them. sanctionsPrograms/Designations count OpenSanctions programmes aimed AT that country (not entities registered there, which would rank the US and India highest). conflictMentions is GDELT coverage volume over 7 days for locations the articles are about, best-effort and often 0 when the API throttles. Both are proxies, not verified measures.",
  generatedAt: new Date().toISOString(),
  sanctionsUpdatedAt: sanctions.updatedAt,
  countries,
};

fs.writeFileSync(
  path.join(ROOT, "src/data/countryRisk.json"),
  `${JSON.stringify(out, null, 2)}\n`,
  "utf8",
);

const worst = Object.entries(countries)
  .sort((a, b) => a[1].securityDelta - b[1].securityDelta)
  .slice(0, 8)
  .map(([name, r]) => `${name} ${r.securityDelta}`)
  .join(", ");
console.log(`Country risk: ${Object.keys(countries).length} countries adjusted. Largest penalties: ${worst}`);
